server:
  #forward-headers-strategy: framework
  port: 8080
  url: https://www.winnticket.store

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.31.35.207:5432/winnticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: winnticket!@#$

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: 127.0.0.1
      port: 6347

logging:
  level:
    kr.co.winnticket: DEBUG

jwt:
  secret: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

file:
  upload-dir: /home/ubuntu/winnticket_upload


# 채널 연동 (베네피아)
benepia:
  seed-key: 5906575fb31548aa
  cust-co-cd: z819
  confirm-url: https://stg-auth.benepia.co.kr/api/token/confirm
  token-create-url: https://stg-auth.benepia.co.kr/api/token/request
  batch-base-url: https://stg-collections.benepia.co.kr
  prdgb-file: ticket
  order-base-url: https://stg-collections.benepia.co.kr
  kcp-co-cd: A8MCD
  api-key: "6ec5212a76b7e632c9da50ef2e778166c425e602ee6f3c60ce79511866013fd8b29d3d61"
  kcp:
    site-cd: A8MCD
    pt-memcorp-cd: 5555
    cert-path: /home/ubuntu/cert/KCP_AUTH_A8MCD_CERT.pem
    private-key-path: /home/ubuntu/cert/KCP_AUTH_A8MCD_PRIKEY.pem
    privateKeyPassword: winn123#@!
    base-url: https://spl.kcp.co.kr

benepia-batch:
  max-file-bytes: 20971520   # 20MB
  retry-count: 3
  retry-sleep-ms: 2000
  work-dir: /home/ubuntu/benepia     # 서버에 쓰기 가능한 경로


# 신용카드 연동
payletter:
  base-url: https://testpgapi.payletter.com #운영 : https://pgapi.payletter.com/
  client-id: pay_test
  payment-api-key: QkY0M0E1N0RCOTQ0MDg2NkM0M0YwMDJCNjI0RDY0QkM=
  search-api-key: MkRBNjA0QjkwREVEQkQyMzQ1NjNDMkMzMEI2NTAyMTc=
  service-name: 페이레터

  return-url: https://13.209.91.167/api/payletter/return
  callback-url:  https://13.209.91.167/api/payletter/callback
  cancel-url: https://13.209.91.167/api/payletter/cancel
  front-url: https://www.winnticket.store

# 파트너 연동 (플러스앤)
plusn:
  base-url: http://partnerdev.tourok.co.kr
  order-company: "148"

# 파트너 연동 (민속촌 코어웍스)
coreworks:
  base-url: http://dev-api.core-works.co.kr:8050
  auth-token: "1505ee1f89cc000efdda3b34ee2485fbd9e50be4943ad0c9acf3ceab7bfc225a"
  channel-cd: "HYUNDAINTOUR"

# 파트너 연동 (웅진)
woongjin:
  base-url: https://channel-api.nolbal.com
  api-token: "bm9sYmFsLTIyLTIwMjUtMDMtMjRUMDc6NTQ6NDAuNjcwMzkz"

# 파트너 연동 (엠에어)
mair:
  mode: dev # dev | prod
  mkno: "HDGH"     # 채널 구분 코드
  mkid: "HDGH1"    # 채널 아이디
  connectTimeoutMs: 2000
  responseTimeoutMs: 5000
  issueUrl: "https://cp.mair.co.kr/dev/_cp_jsonp.asp" # 운영 : https://cp.mair.co.kr/_cp_jsonp.asp
  cancelUrl: "https://cp.mair.co.kr/dev/_cp_cc_jsonp.asp" # 운영 : https://cp.mair.co.kr/_cp_cc_jsonp.asp
  useCheckUrl: "https://cp.mair.co.kr/dev/_cp_use_jsonp.asp" # 운영 : https://cp.mair.co.kr/_cp_use_jsonp.asp

# 파트너 연동 (스파비스)
spavis:
  base-url: "https://www.spavis.co.kr/social_interface/couponif03.asp" # 스파비스 운영 url
  cust-id: 410268 # 채널 코드

# 파트너 연동 (플레이스토리)
playstory:
  base-url: "http://out.dev.pscms.co.kr"
  chn-id: "hyundaiplanandtour"

# 파트너 연동 (스마트인피니(서울랜드))
smartinfini:
  base-url: "https://nsi.smartinfini.com/cinterface"
  token: "BZIG91YGLkcts0U2Uau5Kg=="
  channel-id : "36"

# 뱅크다 연동
bankda:
  url: "https://a.bankda.com/dtsvc/bank_tr.php"
  token: "369fe06f41dbe5efc7b69a28da47bb2f"


# 파트너 연동 (아쿠아플라넷)
aquaplanet:
  url: https://exgatedev.hanwharesort.co.kr:443/iGate/SIF/json.jdo
  system-name: SIF99999
  stn-tmsg-ip: 13.209.91.167
  wrkr-no: l1711019
  envr-dv-cd: D

# 파트너 연동(LS컴퍼니)
lscompany:
  base-url: "https://unity-dev.lscompany-api.com/Api_v3"
  agent-no: "CH2603091"
  token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoic2VsbGVyIiwicGFyYW1zIjp7ImNvZGUiOiJDSDI2MDMwOTEifX0.DCPJ-iJwpeew-UYPRuscjr4MBJRp4MooNFgsn8m-9es"



